config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:new,:create]
  resources :scores
  resources :courses, only: [:index,:show]
  resources :categories, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :scores
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :scores
  
  def self.search(search)
    if search
      where("name LIKE ?","%#{search}%")
    else
      all.order("alphabet ASC")
    end
  end
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image2, Image2Uploader
  belongs_to :score, optional: true
end

app/models/score.rb
class Score < ApplicationRecord
  
  belongs_to :user
  belongs_to :course
  belongs_to :category
  
  # mount_uploader :image3, Image2Uploader
  
  has_many :pictures
  accepts_nested_attributes_for :pictures
  
  validates :score_out, presence: true
  validates :score_in, presence: true
  validates :score_total, presence: true
  validates :put_out, presence: true
  validates :put_in, presence: true
  validates :put_total, presence: true
  validates :memo, length:{maximum: 255}
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_category
  # Mix-in
  # https://techacademy.jp/my/rails/rails5/ruby#chapter-11-3
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def set_category
    @categories=Category.all
  end
  
  
  def counts
    # @count_scores = current_user.scores.where(category_id: category.id).count 
  end  
 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @scores=current_user.scores.where(category_id: params[:id]).page(params[:page])
    @category=Category.find(params[:id])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    @courses=Course.search(params[:search])
    @scores=current_user.scores.all
  end
  
  def show
    @scores=current_user.scores.where(course_id: params[:id]).order('date DESC').page(params[:page])
    @course=Course.find(params[:id])
  end
  
  private
  
  def course_params
    params.require(:course).permit(:name)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  before_action :set_user, only: [:show,:edit,:update]
  
  def index
    @scores = current_user.scores.order('date DESC').page(params[:page])
    @bestscore=current_user.scores.order(:score_total).first
  end

  def new
    @score=Score.new
    2.times { @score.pictures.build }
    @courses=Course.all.order('alphabet ASC')
    @score.put_total = 0
    @score.score_total = 0
  end

  def create
    @score=current_user.scores.build(score_params)
    
    
    if @score.save
      flash[:success]="スコア登録が完了しました"
      redirect_to @score
    else
      @courses=Course.all.order('alphabet ASC')
      flash[:danger]="スコアの登録に失敗しました"
      render :new
    end  
  end

  def destroy
      @score.destroy
      flash[:success]="削除が完了しました"
      path = Rails.application.routes.recognize_path(request.referer)
      if path[:action] == "show"
        redirect_to scores_path
      else
        redirect_back(fallback_location: scores_path)
      end
  end

  def edit
    @courses=Course.all.order('alphabet ASC')
    #@score.image2.cache! unless @score.image2.blank? 
  end

  def update
    if @score.update(update_score_params)
      flash[:success]="編集が完了しました"
      redirect_to @score
    else
      flash[:danger]="編集に失敗しました"
      render :edit
    end  
  end

  def show
    
  end
  
  private
  
  
  def set_user
    @score=current_user.scores.find(params[:id])
  end
  
  def score_params
    params.require(:score).permit(:date,:score_out,:score_in,:score_total,:put_out,:put_in,:put_total,:user,:course_id,:category_id,:memo,:image2_cache, pictures_attributes: [:image2])
  end
  
  def update_score_params
    params.require(:score).permit(:date,:score_out,:score_in,:score_total,:put_out,:put_in,:put_total,:user,:course_id,:category_id,:memo,:image2_cache, pictures_attributes: [:image2, :_destroy, :id])
  end
  
  def correct_user
    @score = current_user.scores.find_by(id: params[:id])
    unless @score
      redirect_to root_url
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def new
    @user=User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def more_zero(c)
    if c == 0
      return "btn-default"
    elsif c < 6
      return "btn-success"
    else
      return "btn-primary"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/categories/show.html.erb
<div class="page-header">
  <h1>
  Score Range &nbsp;&nbsp;<span class="label label-default"><%=@category.score_range%></span>
  <small>&nbsp;&nbsp;Total&nbsp;<%=@scores.select(:id).count%>&nbsp;Rounds</small>
  </h1>
</div>


<% @scores.each do |score|%>
    <div class="col-sm-4">
      <div class="panel panel-<%=score.category.color%>">
        <div class="panel-heading">
          <h4 class="panel-title">Date: <%=score.date%></h4>
            <div class="buttons">
            <%= link_to "Edit", edit_score_path(score.id),class: 'btn btn-success btn-xs' %>
            <%= link_to "Delete", score, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
            </div>
           <h3><%=score.course.name%></h3> 
        </div>
        <div class="panel-body">
          <h4>
            Score: <%=score.score_total%><br>
            Put: <%=score.put_total%>
          </h4>
          <div class="button">
            <%=link_to "Score Detail",score_path(score.id),class: 'btn btn-primary btn-la'%>
          </div>
        </div>
      </div>
   </div> 
<% end %>
<%= paginate(@scores) %>
  

app/views/courses/_courses.html.erb
	  <% courses.pluck(:alphabet).uniq.sort.each do|course_alphabet| %>
		<div class="panel-heading">
			<h3 class="panel-title">
				<a data-toggle="collapse" data-parent="#sampleAccordion" href="#sampleAccordionCollapse1">
					<%=course_alphabet%>
				</a>
			</h3>
		</div>
		<div id="sampleAccordionCollapse1" class="panel-collapse collapse in">
		  <% courses.select{|c|c.alphabet==course_alphabet}.each do|course|%>
			<div class="panel-body">
			  
			  <%= link_to course_path(course.id) do %>
				<h4>
				  <button class="btn <%= more_zero(scores.where(course_id: course.id).count) %>" type="button">
  				  Rounds <span class="badge"><%=scores.where(course_id: course.id).count%></span>
          </button>
				  <%=course.name%>
        </h4>  
				<% end %>
			</div>
			<% end %>
		</div>
		<% end %>
	

app/views/courses/index.html.erb
<h1>Select Golf Course</h1>

<%= form_tag courses_path, :method => 'get' do %>
	<%=text_field_tag :search , params[:search],placeholder:"Keyword.."%>
	<%=submit_tag "Search"%>
<% end %>
<br><br>

<div class="panel-group" id="sampleAccordion">
	<div class="panel panel-default">
	 
	 <%=render 'courses',{courses: @courses, scores: @scores} %>
	 
	</div>
</div>	

app/views/courses/show.html.erb
<div class="page-header">
  <h1><%=@course.name%> Scores<small>&nbsp;&nbsp;Total&nbsp;<%=@scores.select(:id).count%>&nbsp;Rounds</small></h1>
</div>

<div class="datas">
 <h2>&nbsp;<span class="glyphicon glyphicon-flag"></span>&nbsp;&nbsp;Best Score &nbsp;&gt;&gt;&nbsp;<%=@scores.pluck(:score_total).min%>
 <% if @scores.order(:score_total).first.present? %>
   &nbsp;&nbsp;&nbsp;&nbsp;Date:&nbsp;<%= @scores.order(:score_total).first.date %>
 <% else %>
   <p></p>
 <% end %>
 <h2>&nbsp;<span class="glyphicon glyphicon-flag"></span>&nbsp;&nbsp;Average Score &nbsp;&gt;&gt;&nbsp;<%=@scores.average(:score_total)%></h2>
 <h2>&nbsp;<span class="glyphicon glyphicon-flag"></span>&nbsp;&nbsp;Yearly Average &nbsp;&gt;&gt;&nbsp;<%@scores.group('Year(date)').average(:score_total).map{|k,v| [k,v.to_f]}.to_h.each do|year,year_average|%>
 Y:&nbsp;<%=year%>&nbsp;/&nbsp;<%=year_average%>&nbsp;&nbsp;&nbsp;
 <% end %>
</h2>
</div>

 <% @scores.each do |score|%>
    <div class="col-sm-4">
      <div class="panel panel-<%=score.category.color%>">
        <div class="panel-heading">
          <h4 class="panel-title">Date: <%=score.date%></h4>
            <div class="buttons">
            <%= link_to "Edit", edit_score_path(score.id),class: 'btn btn-success btn-xs' %>
            <%= link_to "Delete", score, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
            </div>
           <h3><%=score.course.name%></h3> 
        </div>
        <div class="panel-body">
          <h4>
            Score: <%=score.score_total%><br>
            Put: <%=score.put_total%>
          </h4>
          <div class="button">
            <%=link_to "Score Detail",score_path(score.id),class: 'btn btn-primary btn-la'%>
          </div>
        </div>
      </div>
   </div> 
<% end %>
<%= paginate(@scores) %> 

 

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Score Card MGR</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Create New Score',new_score_path(current_user)  %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'All Scores',scores_path(current_user) %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Scores by Courses',courses_path(current_user) %></li>
              </ul>
            </li>
            <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Score Range Select<span class="caret"></span></a>
             <ul class="dropdown-menu">
               
               <% @categories.each do |category|%>
               <li><a href="/categories/<%=category.id%>"><%=category.score_range%>
               
                <%#<span class="badge"><%= @count_scores% ></span>%>
                   
                   </a>
               </li>
               <% end %>
             </ul>    
            </li>  
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Signup', signup_path %></li>
          <li><%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>GolfScore3</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
        <%= render 'layouts/flash_messages' %>
      <%= yield %>
      
    </div>
    <script>
      $(function(){
        $('#score_score_out').change(function(){
          $("#score_score_total").val(parseInt($("#score_score_out").val()) + parseInt($("#score_score_in").val()));
        });
        
        $('#score_score_in').change(function(){
          $("#score_score_total").val(parseInt($("#score_score_out").val()) + parseInt($("#score_score_in").val()));
        });
        
        $('#score_put_out').change(function(){
          $("#score_put_total").val(parseInt($("#score_put_out").val()) + parseInt($("#score_put_in").val()));
        });
        
        $('#score_put_in').change(function(){
          $("#score_put_total").val(parseInt($("#score_put_out").val()) + parseInt($("#score_put_in").val()));
        });
      });
    </script>
  </body>
</html>

app/views/scores/create.html.erb
<h1>Scores#create</h1>
<p>Find me in app/views/scores/create.html.erb</p>

app/views/scores/destroy.html.erb
<h1>Scores#destroy</h1>
<p>Find me in app/views/scores/destroy.html.erb</p>

app/views/scores/edit.html.erb
<h1>Edit Score</h1>

<%=form_for(@score)do|f|%>

<%= f.label :date,"Date (Year/Month/Day)" %>
<%= f.date_select :date, {:date_separator => "Please select"},class:"form-control",value: @score.date %>

<%= f.label :course_id,"Course Select" %>
<%= select_tag 'score[course_id]', options_from_collection_for_select(@courses, :id, :name,@score.course.id),class:"form-control"%>


<%= f.label :score_out,"Score (Out)" %>
<%= f.text_field :score_out,class:"form-control",value: @score.score_out %>

<%= f.label :score_in,"Score (In)" %>
<%= f.text_field :score_in,class:"form-control",value: @score.score_in %>

<%= f.label :score_total,"Total Score" %>
<%= f.text_field :score_total,class:"form-control",value: @score.score_total %>

<%= f.label :category_id,"Score Range Select" %>
<%= select_tag 'score[category_id]', options_from_collection_for_select(@categories, :id, :score_range,@score.category.id),class:"form-control" %>


<%= f.label :put_out,"Put (Out)" %>
<%= f.text_field :put_out,class:"form-control",value: @score.put_out %>

<%= f.label :put_in,"Put (In)" %>
<%= f.text_field :put_in,class:"form-control",value: @score.put_out %>

<%= f.label :put_total,"Total Put" %>
<%= f.text_field :put_total,class:"form-control",value: @score.put_total %>

<%= f.label :memo,"Comment (Option,max 255)" %>
<%= f.text_field :memo,class:"form-control" %>

<%# @score.pictures.each do |picture|%>
  <%#= image_tag(picture.image2.thumb.url) if @score.pictures.exists? %>
  <%#= f.label(:image2, "Attach Picture (Option)") %>
  <%#= f.file_field(:image2, class:"form-control")%>
  <%#= f.hidden_field :image2_cache %>
<%# end %>

<%if @score.pictures.exists? %>
  <%= f.fields_for(:pictures) do |picture| %>
    <%= image_tag(picture.object.image2.thumb.url) %>
    <%= picture.file_field(:image2) %>
    <%= picture.hidden_field :id, value: picture.object.id %>
  <% end %>
<% else %>
  <%= f.fields_for :pictures do |picture|%>
  <%= picture.file_field :image2%>
  <% end %>
<% end %>
 

<%=f.submit "Update",class: 'btn btn-primary btn-md'%>
<% end %>

app/views/scores/index.html.erb
<div class="page-header">
  <h1>All Scores<small>&nbsp;&nbsp;Total&nbsp;<%=@scores.select(:id).count%>&nbsp;Rounds</small></h1>
</div>

<div class="datas">
 <% if @bestscore.present? %>
   <h2>&nbsp;<span class="glyphicon glyphicon-flag"></span>&nbsp;&nbsp;Best Score &nbsp;&gt;&gt;&nbsp;<%=@bestscore.score_total%></h2>
 
   <h2 style="color: yellow;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;Date:&nbsp;<%=@bestscore.date%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Course:&nbsp;<%=@bestscore.course.name%>&nbsp;-</h2>
 <% else %>
   <h2>&nbsp;<span class="glyphicon glyphicon-flag"></span>&nbsp;&nbsp;No Score</h2>
 <% end %>
 <% if @scores.present? %>
   <h2>&nbsp;<span class="glyphicon glyphicon-flag"></span>&nbsp;&nbsp;Average Score &nbsp;&gt;&gt;&nbsp;<%=@scores.average(:score_total)%></h2>
   <h2>
     &nbsp;<span class="glyphicon glyphicon-flag"></span>&nbsp;&nbsp;Yearly Average &nbsp;&gt;&gt;&nbsp;<%@scores.group('Year(date)').average(:score_total).map{|k,v| [k,v.to_f]}.to_h.each do|year,year_average|%>
     Y:&nbsp;<%=year%>&nbsp;/&nbsp;<%=year_average.to_f%>&nbsp;&nbsp;&nbsp;
     <% end %>
    </h2>
 <% else %>
   <p></p>
 <% end %>
</div>

  
<% @scores.each do |score|%>
    <div class="col-sm-4">
      <div class="panel panel-<%=score.category.color%>">
        <div class="panel-heading">
          <h4 class="panel-title">Date: <%=score.date%></h4>
            <div class="buttons">
            <%= link_to "Edit", edit_score_path(score.id),class: 'btn btn-success btn-xs' %>
            <%= link_to "Delete", score, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
            </div>
           <h3><%=score.course.name%></h3> 
        </div>
        <div class="panel-body">
          <h4>
            Score: <%=score.score_total%><br>
            Put: <%=score.put_total%>
          </h4>
          <div class="button">
            <%=link_to "Score Detail",score_path(score.id),class: 'btn btn-primary btn-la'%>
          </div>
        </div>
      </div>
   </div> 
<% end %>
<%= paginate(@scores) %>

app/views/scores/new.html.erb
<h1>Create New Score</h1>

<div class="form-horizontal" role="form" id="scores">
    <%=form_for(@score)do|f|%>
    
        <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="form-group">
            <%= f.label :date,"Date (Year/Month/Day)",class:"control-label col-sm-2"%>
            <div class="col-sm-10">
                <%= f.date_select :date, {:date_separator => "Please select"},class:"form-control"%>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :course_id,"Course Select",class:"control-label col-sm-2"%>
            <div class="col-sm-10">
                <%= select_tag 'score[course_id]', options_from_collection_for_select(@courses, :id, :name),class:"form-control"%>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :score_out,"Score (Out)",class:"control-label col-sm-2"%>
            <div class="col-sm-10">
                <%= f.text_field :score_out,class:"form-control"%>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :score_in,"Score (In)",class:"control-label col-sm-2"%>
            <div class="col-sm-10">
                <%= f.text_field :score_in,class:"form-control"%>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :score_total,"Total Score",class:"control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :score_total,class:"form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :category_id,"Score Range Select",class:"control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= select_tag 'score[category_id]', options_from_collection_for_select(@categories, :id, :score_range),class:"form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :put_out,"Put (Out)",class:"control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :put_out,class:"form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :put_in,"Put (In)",class:"control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :put_in,class:"form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :put_total,"Total Put",class:"control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :put_total,class:"form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :memo,"Comment (Option,max 255)",class:"control-label col-sm-2" %>
            <div class="col-sm-10">
                <%= f.text_field :memo,class:"form-control" %>
            </div>
        </div>
        
        <div class="form-group">
            <%= f.label :image2,"Attach Picture (Option)",class:"control-label col-sm-2"%>
           <div class="col-sm-10">
                <%= f.fields_for :pictures do |picture|%>
                <%= picture.file_field :image2%>
                <% end %>
            </div>
        </div>
           
        
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%=f.submit "Submit",class:"btn btn-primary btn-lg btn-block"%>
            </div>
        </div>    
    <% end %>
</div>

app/views/scores/show.html.erb
<div class="page-header">
  <h1>My Score
    <small>
      &nbsp;&nbsp;Date:&nbsp;<%=@score.date%>&nbsp;
      <%= link_to "Edit", edit_score_path(@score.id),class: 'btn btn-success btn-md' %>
      <%= link_to "Delete", @score, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-md' %>
    </small>
  </h1>
</div>

<div class="panel panel-<%=@score.category.color%>">
  <div class="panel-heading"><h2><%=@score.course.name%></h2></div>
  <div class="panel-body">
    <h2>&nbsp;&nbsp;&nbsp;SCORE:&nbsp;&nbsp;  OUT&nbsp;&nbsp;<%=@score.score_out%>&nbsp;+&nbsp;IN&nbsp;&nbsp;<%=@score.score_in%>&nbsp;=&nbsp;&nbsp;&nbsp;<span style="color:#ff0000; font-size:40px;">TOTAL&nbsp;&nbsp;&nbsp;<%=@score.score_total%></span></h2>
    <h3 style="color: gray;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Putting:&nbsp;&nbsp; OUT&nbsp;&nbsp;<%=@score.put_out%>&nbsp;+&nbsp;IN&nbsp;&nbsp;<%=@score.put_in%>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(Total Put:&nbsp;&nbsp;<%=@score.put_total%>)</h3>
    <div class="comment">
      <hr>
      <h3>Comment:&nbsp;&nbsp; <%=@score.memo%></h3>
    </div>
  </div>
</div>

<%# if @score.pictures.image2? %>
　　<%#= image_tag @score.pictures.image2.url %>
　<%# else %>
　　<%#= image_tag 'noimage.gif' %>
　<%# end %>
　
<% if @score.pictures.exists? %>
  <ul>
    <% @score.pictures.each do |picture| %>
      <li><%= image_tag(picture.image2.url) %></li>
    <% end %>
  </ul>
<% else %>
   <%= image_tag 'noimage.gif' %>
<% end %>　

app/views/scores/update.html.erb
<h1>Scores#update</h1>
<p>Find me in app/views/scores/update.html.erb</p>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <h3 style="color: #316745;">logged_in player: <%= current_user.name %></h3>
   <div class="center jumbotron toppage_container">
    <div>
      <div class="text-left flex_piller padding_top">
        <h1>Menu</h1>
        <h2>New Score: <%= link_to 'Create!', new_score_path, class: 'btn btn-la btn-info' %></h2>

        <h2>Go My Scores: <%= link_to 'All Scores!', scores_path, class: 'btn btn-la btn-success' %>       
        <h2>Golf Courses: <%= link_to 'Scores by Courses!', courses_path, class: 'btn btn-la btn-warning' %></h2> </h2>
        
      </div>
    </div>
   </div>
<% else %>  
  <div class="center jumbotron welcome_page margin_top">
    <div class="text-center">
      <h1>Welcome to the Golf Score MGR</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>  

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>